/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./pages/**/*.html",
    "./templates/**/*.html",
    "./privacy.html",
    "./js/**/*.js",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#cde5ff",
        "surface-bright": "#fffcf5",
        "primary-dim": "#5f531a",
        "on-secondary-fixed": "#004369",
        "outline-variant": "#b8b29f",
        "primary": "#f5e2a1",
        "on-tertiary-fixed-variant": "#673c2e",
        "background": "#fffcf5",
        "outline": "#807a6a",
        "secondary": "#31638a",
        "surface-container-highest": "#eae2ce",
        "inverse-on-surface": "#a19c92",
        "on-surface": "#000000",
        "on-primary-container": "#000000",
        "inverse-surface": "#100e08",
        "tertiary-dim": "#754739",
        "tertiary": "#835344",
        "on-secondary": "#f6f9ff",
        "on-background": "#000000",
        "surface": "#fffcf5",
        "surface-container": "#f4eddd",
        "primary-container": "#f5e2a1",
        "on-error-container": "#6e1400",
        "on-surface-variant": "#000000",
        "on-tertiary": "#fff7f5",
        "secondary-dim": "#22577e",
        "inverse-primary": "#f7e59d",
        "surface-tint": "#f5e2a1",
        "surface-variant": "#eae2ce",
        "on-error": "#fff7f6",
        "secondary-fixed-dim": "#b1d9ff",
        "on-tertiary-container": "#5d3326",
        "surface-container-low": "#fffcf5",
        "primary-fixed": "#f5e2a1",
        "error-dim": "#791903",
        "on-secondary-fixed-variant": "#2c5f87",
        "secondary-container": "#fff9ed",
        "tertiary-fixed-dim": "#e4a896",
        "on-secondary-container": "#20567c",
        "surface-dim": "#e1dac6",
        "surface-container-high": "#fffaf0",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#000000",
        "on-tertiary-fixed": "#442014",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#f3b5a3",
        "tertiary-container": "#f3b5a3",
        "primary-fixed-dim": "#e6d48e",
        "on-primary": "#000000",
        "error-container": "#fd795a"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
    },
  },
  safelist: [
    // Dynamically constructed in footer-init.js: 'bg-gradient-to-t from-' + fromColor + ' to-transparent'
    'from-white',
  ],
  plugins: [require('@tailwindcss/forms')],
}
